### PR TITLE
Added Squadcast.com to Incident management tools

### PR DESCRIPTION
**Pull request by muthali**

### CODE REVIEW

**Comment by meirwah** [comment]
@muthali this seems more DEVOPS related than cyber/security, so not sure this list makes sense for it

**Comment by muthali** [comment]
Found pagerduty on the list of tools. Squadcast is very similar to
pagerduty.

**Comment by meirwah** [comment]
i'm closing this one, this list is focused at cyber/security IR

**Comment by muthali** [comment]
Cool, thanks!

**Pull request closed without merging**
