### PR TITLE
In mid-2022 BT3 was discontinued.

### PR DESCRIPTION
**Pull request by deltajuliet**

### CODE REVIEW

**Comment by meirwah** [comment]
why not simply remove it totally from list ?

**Comment by deltajuliet** [comment]
The tooling still exists it’s just no longer supported and only runs in offline mode. So my thought with a strike through is that it references the tooling but sets expectations that it’s going away. I can agree with just removing it as well.

**Comment by meirwah** [comment]
ok, plz remove it totally

**Comment by stuhli** [comment]
Addressed with https://github.com/meirwah/awesome-incident-response/pull/223

**Pull request closed without merging**
