### PR TITLE
Added two keithjjones tools.

### PR DESCRIPTION
**Pull request by keithjjones**
Added two tools I wrote.  I'm working on adding more functionality to fileintel.  hostintel is more mature.

### CODE REVIEW

**Comment by meirwah** [comment]
Heyy @keithjjones ,
These 2 projects seem interesting, but also seem to be yet immature (just released)...
Can we give this some time (to gain traction) and then publish it on this list?

In the meantime I can offer some other channels to publish these projects...

**Comment by keithjjones** [comment]
It's up to you. They have been used in multiple active investigations already.  Myself and my colleagues have been using them successfully for a while now so I figured I would share with the community.  Any additional channels that you suggest I'd be happy to look at.

**Comment by meirwah** [comment]
sure, you can find some here : https://medium.com/@meirwah/dfir-community-resource-list-1388b1dd505e

Another place is here : http://www.dfir.training/index.php/tools/advanced-search

**Comment by keithjjones** [comment]
In case you haven't been checking, both of these projects are up to 8 stars and a few forks.  They were also added to the awesome malware list.

Thanks!

**Comment by keithjjones** [comment]
Added another new tool.  Since this hasn't been merged there are 3 tools queued up on this pull request.

**Comment by meirwah** [comment]
looks good.. 
Sorry for late response, was in a long vacation...

**Pull request merged**
