### PR TITLE
Add KAPE to Windows Evidence Collection

### PR DESCRIPTION
**Pull request by rathbuna**

### CODE REVIEW

**Comment by rathbuna** [comment]
https://github.com/meirwah/awesome-incident-response/pull/128 appears to have issues so this one should negate that old PR.

**Comment by meirwah** [comment]
@rathbuna this tool already exists at https://github.com/meirwah/awesome-incident-response#incident-management

**Comment by rathbuna** [comment]
When I get to a computer I'll move it from there. It's not an incident management tool.

**Comment by rathbuna** [comment]
@meirwah check now

**Comment by meirwah** [comment]
👍

**Pull request merged**
