### PR TITLE
Add True Positive

### PR DESCRIPTION
**Pull request by veeral-patel**
Hi @meirwah! Adding a tool that I've built for case management.

### CODE REVIEW

**Comment by veeral-patel** [comment]
@meirwah Hey Meir - have you looked at this PR? It's just a one line change; you should be able to review it and merge it within 10 seconds!

**Comment by meirwah** [comment]
Hey @veeral-patel ,
Usually I add to the project open source project that have serious traction (like many github stars)
or free projects/tools which have showed massive usage from the community.
Can you show either of those in the project you suggest ?

**Comment by veeral-patel** [comment]
@meirwah Hey - the product is closed-source but it has a free tier (like Demisto). It doesn't have massive usage, but it's a useful tool for the community, and adding it would make this list more useful!

**Comment by meirwah** [comment]
Ok, so let's do this..
give it some time to gain traction, post here some evidence for that traction , and reopen this ticket once you have those...

For now will close the ticket..

**Pull request closed without merging**
