### PR TITLE
Add DumpIt and Redline

### PR DESCRIPTION
**Pull request by JohnTroony**
DumpIt is a Windows memory imaging tool. It makes use of win32dd and win64dd. Redline on the other hand, is a all in one tool that can assist in development of a threat assessment profile.

### CODE REVIEW

**Comment by meirwah** [comment]
Heyy,
Thanks for the contrib! but..
Please note DumpIt was already added : https://github.com/meirwah/awesome-incident-response#windows-evidence-collection.

Please remove it , and I will merge the PR for the Redline tool.

**Comment by meirwah** [comment]
@JohnTroony Please see #18

**Comment by JohnTroony** [comment]
Okay... Seems I wasn't keen on checking the list of tools. I'll make the changes and send a PR. Thanks

**Comment by JohnTroony** [comment]
Oh, Seems like you've already merged the commit. No need to send another PR right?

**Pull request merged**
