### PR TITLE
Remove Security Onion Linux Distro

### PR DESCRIPTION
**Pull request by hslatman**
Reasons: It's mainly aimed at monitoring and detection, Does contain
some tools for IR, but the complete distro is IMO not specific enough
to IR. Also the Network Security Monitoring category seems off in
Awesome Incident Response.

### CODE REVIEW

**Comment by meirwah** [comment]
Not sure about this one, let me add @exp0se who added this tool to this thread...
To hear his POV on this...

**Comment by hslatman** [comment]
Sure!

**Comment by sroberts** [comment]
I mean, isn't monitoring & detection a part of the incident response process? I look at IR as a combination of a number of disciplines including Forensics, Malware Analysis, and Intrusion detection. I'd argue this does make sense in this.

**Comment by hslatman** [comment]
When looking at it like a timeline, you could picture it like this:

Monitoring -> Detection -> Incident Response (forensic evidence collection, initial forensics) -> Deeper Forensics (say, when initial hits 1 hour). 

Malware Analysis can be described as part of the deeper forensics, if you ask me, which can take quite long (like Stuxnet analysis).

**Comment by exp0se** [comment]
I use it in IR a lot, suppose you've got some indicators from some machine during investigation - you can then add them to SO and quickly find all infected machines. 

Or suppose you've got called in to investigate suspicious host, but you didn't find anything weird(rootkit scenario) - then you can use SO to check network traffic from this host. Way too useful to remove IMO.

**Comment by hslatman** [comment]
Ok, that sounds fine. Then I suggest a change of category(name) only.

**Pull request closed without merging**
