### PR TITLE
Awesome List style guide conformance fixes and cleanup.

### PR DESCRIPTION
**Pull request by meitar**
This pull request contains several commits whose purpose is to make the contents of the Awesome Incident Response list conform more strictly to the Awesome List style guide. The style guide requests numerous things, including but not limited to the following:

* Name of list as the top-level heading.
* Awesome badge placed to the right of the title, not underneath.
* Description of the list contents.
* All line items should end in appropriate punctuation (like a period).
* Removing prepositions ("A," "An," "The," etc) from the start of items.
* Removing duplicated line item names from their descriptions.
* Expanding acronyms of line item names in the link itself.

The above list is what this pull request performs. These changes are not an exhaustive treatment of the style guide, but rather just a first pass that I took while reading through the list today. :)

### CODE REVIEW

**Comment by meirwah** [comment]
Thanks for the PR @meitar , 
Will need some time to review this deeply, can you update from master to resolve conflicts?

**Comment by meitar** [comment]
@meirwah Sure, no worries. I'm not sure how I accidentally closed this but I didn't mean to. I've rebased against your current `master` branch and everything should be up-to-date now.

**Comment by meitar** [comment]
@meirwah I have rebased this again so it's (once again) easy for you to merge. As a reminder, this branch is a set of style guide fixes. The contents are not changed.

**Comment by meitar** [comment]
@meirwah Thanks for the quick response. :)

**Comment by meirwah** [comment]
👍

**Pull request merged**
