### PR TITLE
Crowd Response by CrowdStrike Added

### PR DESCRIPTION
**Pull request by hslatman**

### CODE REVIEW

**Comment by meirwah** [comment]
why direct link to a zip file?

**Comment by hslatman** [comment]
Other links basically all arrive at a specific page for a single tool. CrowdStrike only offers a generic page for all its tools, so user has to look for it. Thought this was appropriate, but linking to generic page is also possible

Sent from my Windows Phone
________________________________

**Comment by meirwah** [comment]
It seems that all their tools are offered as services... which tool exactly is the downloaded tool?

**Comment by hslatman** [comment]
Just replaced the link to the community tools page. There are some non-IR tools there, like Heartbleed scanner. Still an interesting page for security professionals.

**Pull request merged**
