### PR TITLE
Add Registry + Bstrings

### PR DESCRIPTION
**Pull request by meirwah**

### CODE REVIEW

**Comment by meirwah** [comment]
fixes #47

**Comment by EricZimmerman** [comment]
well, the Registry project by itself doesnt really DO anything. its just the parser. rather, link Registry Explorer, ShellBags Explorer, PECmd, AmCacheParser, and AppCompatParser.

bstrings is at its heart a strings tool, but it does a ton more than that such as built in Regex for common things like UNC paths, URLs, emails, credit card #s, etc.

**Comment by meirwah** [comment]
ok.. so If you had 2 choose 2 tools, and provide a short 1 line description of each..
what would it be?

**Comment by EricZimmerman** [comment]
id say Registry Explorer and ShellBags Explorer, from a capabilities
perspective.

Registry Explorer: Registry viewer with deleted key/value support,
loading of multiple hives, and robust searching

ShellBags Explorer: Visually explore a users activity including files,
directories, network resources and more


why only 2 tools tho? if theres 6 best of tools available, why limit people?

**Comment by meirwah** [comment]
You can see that I try to keep the list not biased, meaning that there is no 1 vendor/creator that most tools belong to him, if I add at once 6 tools from same vendor at once, it might change that.

Moreover I try to keep the list to represent the best tools out there, It hard for me sometimes to tell which are the best, so I usually look for amount of GitHub stars/feedback from the community.
Since I don't have such indications for all tools you mentioned, I asked you to point me to the most important ones...

**Comment by EricZimmerman** [comment]
well i have seen projects with a bunch of stars on github that are flat
out wrong and/or provide far less features, so trusting in crowd
sourcing doesnt seem like a good way to determine "best"

thanks for the info

**Comment by meirwah** [comment]
That's true Eric, but that's the best way I can think on right now...
What other method you purpose? How would you determine what goes in and what not?

**Comment by EricZimmerman** [comment]
as to my software, i would recommend looking over my blog where things
get explained. from there you can make a decision as to the
veracity/usefulness as compared to other solutions.

to limit things to 2 things per vendor could mislead people to use a
tool listed when there are better alternatives out there IMO.

its a tough balance for sure, but at the end of the day, your name is on
the list. i would recommend at least a cursory review of everything

Thanks!

**Comment by meirwah** [comment]
@EricZimmerman can you provide the url's to this projects?
It's not lear to me where are the Github project pages for these (Registry Explorer and ShellBags Explorer)....

**Comment by EricZimmerman** [comment]
Those are not open source as end users would need $1000s in 3rd party controls to compile it. I typically do not open source GUIs as I use the same 3rd party controls heavily in all my GUIs. command line tools are a different story which is why you can see things like RECmd on my Github account

The links are here:

http://binaryforay.blogspot.com/p/software.html

**Comment by meirwah** [comment]
Look at this PR : https://github.com/meirwah/awesome-incident-response/pull/53/files
WDYT?

**Comment by EricZimmerman** [comment]
Looks great! and thanks!!

**Pull request closed without merging**
