### PR TITLE
API list

### PR DESCRIPTION
**Pull request by deralexxx**
added a list of APIs useful for security people

### CODE REVIEW

**Comment by meirwah** [comment]
Hey @deralexxx ,
Your list looks really awesome! but not sure it fits the "Other Tools" section, since it's not exactly
a tool (like the rest of this section).
I'm thinking of waiting for more lists like this, and once we have some , add a section for "alternate/related awesome lists", WDYT?

**Comment by deralexxx** [comment]
Agree

**Comment by deralexxx** [comment]
@meirwah changed my commit, hopefully that one is better :-)

**Comment by meirwah** [comment]
change to "Other Awesome Lists"

and add a link in Contents...

**Comment by deralexxx** [comment]
hope that one is good for merge

**Comment by meirwah** [comment]
@deralexxx plz note the list is in alphabetical order.. please place in right location

**Comment by meirwah** [comment]
👍

**Pull request merged**
